print ("Hello World!!!")
print ("Hello Again")
print ("Is it me you are looking for?")
print ("Prolly not lol!")
print ("Anyway, i like typing this.")
print ("This is Fun!.")
print ('Yay! Printing.')
print ("I'd much rather you'not'.")
print ('I "said" do not touch this.')
print ("Lets see if Print works")
print ("Print does not work, so just stick to 'print'")
